# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :node1 do |node1|
    node1.vm.box = "ubuntu/trusty64"
    node1.vm.hostname = "node1"
    node1.vm.network :private_network, ip: "10.1.1.101"
    node1.vm.network :private_network, ip: "10.1.2.101"
    #end
  end
  config.vm.define :node2 do |node2|
    node2.vm.box = "ubuntu/trusty64"
    node2.vm.hostname = "node2"
    node2.vm.network :private_network, ip: "10.1.1.102"
    node2.vm.network :private_network, ip: "10.1.2.102"
  end
  config.vm.define :dns do |dns|
    dns.vm.box = "ubuntu/trusty64"
    dns.vm.hostname = "dns"
    dns.vm.network :private_network, ip: "10.1.1.103"
  end
end
